# Generated by Django 3.1.7 on 2021-04-20 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter title of content', max_length=200)),
                ('image', models.ImageField(upload_to='content')),
                ('description', models.TextField(blank=True)),
                ('draft', models.BooleanField(default=True)),
                ('content_type', models.CharField(max_length=200)),
            ],
        ),
    ]
