# Generated by Django 3.1.7 on 2021-04-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exapp', '0002_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='user',
        ),
        migrations.AddField(
            model_name='reviews',
            name='e_mail',
            field=models.EmailField(default='None', max_length=254),
        ),
        migrations.AddField(
            model_name='reviews',
            name='firstname',
            field=models.CharField(default='', help_text='Enter user firstname', max_length=200),
        ),
        migrations.AddField(
            model_name='reviews',
            name='name',
            field=models.CharField(default='', help_text='Enter user name', max_length=200),
        ),
    ]
