# Generated by Django 3.1.7 on 2021-04-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exapp', '0003_auto_20210420_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='e_mail',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
